
package com.unisinsight.vdp.core.manager.integration.vms.pre.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VideoManager", targetNamespace = "http://webservice.arges.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VideoManager {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVideoFile", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetVideoFile")
    @ResponseWrapper(localName = "getVideoFileResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetVideoFileResponse")
    public String getVideoFile(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    FtpServer arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    int arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    int arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    long arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    long arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    int arg7);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cameraCapture", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.CameraCapture")
    @ResponseWrapper(localName = "cameraCaptureResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.CameraCaptureResponse")
    public String cameraCapture(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapture", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetCapture")
    @ResponseWrapper(localName = "getCaptureResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetCaptureResponse")
    public String getCapture(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    long arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    long arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordPlayUrl", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetRecordPlayUrl")
    @ResponseWrapper(localName = "getRecordPlayUrlResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetRecordPlayUrlResponse")
    public String getRecordPlayUrl(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    String arg6);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTreeNode", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetTreeNode")
    @ResponseWrapper(localName = "getTreeNodeResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetTreeNodeResponse")
    public String getTreeNode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMediaPalyUrl", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetMediaPalyUrl")
    @ResponseWrapper(localName = "getMediaPalyUrlResponse", targetNamespace = "http://webservice.arges.com/", className = "com.unisinsight.vdp.core.manager.integration.vms.pre.webservice.GetMediaPalyUrlResponse")
    public String getMediaPalyUrl(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    int arg4);

}
